name: SilverUtil
main: io.github.Alligrater.SilverUtil
version: 2.3
commands:
  suname: 
    description: Change your item name
    usage: /suname [Itemname]
  sulore: 
    description: Set your item lore
    usage: /sulore [add/remove/set]
  bling: 
    description: Ping someone privately
    usage: /bling [Playername]
  spam: 
    description: Spam on the screen
    usage: /spam [Message]
  mutebling: 
    description: Mute chat sound fx
    usage: /mutebling
  gift: 
    description: Give your friend a gift
    usage: /gift [Playername]
  loca: 
    description: Show others your location
    usage: /loca
  viewonline: 
    description: View all players online
    usage: /viewonline
  rtp: 
    description: Teleport to a random spot
    usage: /rtp [Playername]
  monk: 
    description: Vow of poverty.
    usage: /monk
  redbag: 
    description: send redbag
    usage: /redbag [claim/send]
  impost: 
    description: faking someone say somethin'
    usage: /impost [name] [message]
  say: 
    description: Say it out, but raw
    usage: /say [message]
  marry: 
    description: Confess your love
    usage: /marry [Playername]
  getdrop: 
    description: get loot gained from ops
    usage: /getdrop [Playername]
  saylocal: 
    description: say locally
    usage: /saylocal [Message]