name: SilverUtil
main: io.github.Alligrater.SilverUtil
version: 1.0
commands:
  suench: 
    description: Add an enchant to your item
    usage: /suench [add/remove/list]
  suname: 
    description: Change your item name
    usage: /suname [Itemname]
  sulore: 
    description: Set your item lore
    usage: /sulore [add/remove/set]
  bling: 
    description: Ping someone privately
    usage: /bling [Playername]
  spam: 
    description: Spam on the screen
    usage: /spam [Msg]
  mute: 
    description: Mute chat sound fx
    usage: /mute
  gift: 
    description: Give your friend a gift
    usage: /gift [Playername]
  loca: 
    description: Show others your location
    usage: /loca
  viewonline: 
    description: View all players online
    usage: /viewonline
 